# filtering

In [8]:
import cv2 as cv
import matplotlib.pyplot as plt
import numpy as np

In [9]:
im1=cv.imread("C:/Users/SN124/image/ben 100.jfif")
print(im1)

[[[ 1 13 13]
  [ 3 13 13]
  [ 8 13 16]
  ...
  [16 14 14]
  [16 14 14]
  [16 14 14]]

 [[ 5 13 13]
  [ 5 13 13]
  [ 9 12 16]
  ...
  [16 14 14]
  [16 14 14]
  [16 14 14]]

 [[11 13 13]
  [11 13 14]
  [13 12 16]
  ...
  [17 15 15]
  [17 15 15]
  [17 15 15]]

 ...

 [[23  6  9]
  [21  7  9]
  [16  8  9]
  ...
  [ 6  8  9]
  [ 6  8  9]
  [ 6  8  9]]

 [[21  7  9]
  [20  7  9]
  [16  8  9]
  ...
  [ 6  8  9]
  [ 6  8  9]
  [ 6  8  9]]

 [[16  8  9]
  [14  8  9]
  [13  8  9]
  ...
  [ 6  8  9]
  [ 6  8  9]
  [ 6  8  9]]]


# filter2d

In [10]:
kernal=np.ones((5,5),np.float32)/25
filter=cv.filter2D(im1,-1,kernal)

# blur

In [11]:
blur= cv.blur(im1,(3,3))

# Gaussian blur

In [12]:
Gblur=cv.GaussianBlur(im1,(7,7),0)

# bilateral filter

In [13]:
print(im1.shape)

(237, 213, 3)


In [15]:
Bfilter=cv.bilateralFilter(im1,9,50,50)

# median filter

In [16]:
medianfilter= cv.medianBlur(im1,5)

# Laplacian Filter

In [20]:
img=cv.imread('C:/Users/SN124/image/ben 100.jfif',0)
lap=cv.Laplacian(img,cv.CV_64F,ksize=3)
cv.imshow('image',img)
cv.imshow('laplacian',lap)
cv.waitKey(0)
cv.destroyAllWindows()

In [21]:
img

array([[12, 12, 13, ..., 14, 14, 14],
       [12, 12, 13, ..., 14, 14, 14],
       [13, 13, 13, ..., 15, 15, 15],
       ...,
       [ 9,  9,  9, ...,  8,  8,  8],
       [ 9,  9,  9, ...,  8,  8,  8],
       [ 9,  9,  9, ...,  8,  8,  8]], dtype=uint8)

# sobel Filter

In [30]:
img=cv.imread('C:/Users/SN124/Downloads/mm.jpg',0)
sobelx=cv.Sobel(img,cv.CV_64F,1,0,ksize=-3)
sobelx=np.uint8(np.absolute(sobelx))
cv.imshow('image',img)
cv.imshow('sobelx',sobelx)
cv.waitKey(0)
cv.destroyAllWindows()

In [ ]:
sobely=cv.Sobel(img,cv.CV_64F,0,1,ksize=-3)
sobely=np.uint8(np.absolute(sobely))
cv.imshow('image',img)
cv.imshow('sobelx',sobely)
cv.waitKey(0)
cv.destroyAllWindows()