k-means clustering

In [6]:
#pip install opencv

In [7]:
import cv2 as cv
import numpy as np

In [13]:
img=cv.imread("C:/Users/SN124/image/ben 100.jfif")
img

array([[[ 1, 13, 13],
        [ 3, 13, 13],
        [ 8, 13, 16],
        ...,
        [16, 14, 14],
        [16, 14, 14],
        [16, 14, 14]],

       [[ 5, 13, 13],
        [ 5, 13, 13],
        [ 9, 12, 16],
        ...,
        [16, 14, 14],
        [16, 14, 14],
        [16, 14, 14]],

       [[11, 13, 13],
        [11, 13, 14],
        [13, 12, 16],
        ...,
        [17, 15, 15],
        [17, 15, 15],
        [17, 15, 15]],

       ...,

       [[23,  6,  9],
        [21,  7,  9],
        [16,  8,  9],
        ...,
        [ 6,  8,  9],
        [ 6,  8,  9],
        [ 6,  8,  9]],

       [[21,  7,  9],
        [20,  7,  9],
        [16,  8,  9],
        ...,
        [ 6,  8,  9],
        [ 6,  8,  9],
        [ 6,  8,  9]],

       [[16,  8,  9],
        [14,  8,  9],
        [13,  8,  9],
        ...,
        [ 6,  8,  9],
        [ 6,  8,  9],
        [ 6,  8,  9]]], dtype=uint8)

In [14]:
imgrgh=cv.cvtColor(img,cv.COLOR_BGR2RGB)

In [15]:
vec=imgrgh.reshape((-1,3))

In [16]:
vec

array([[13, 13,  1],
       [13, 13,  3],
       [16, 13,  8],
       ...,
       [ 9,  8,  6],
       [ 9,  8,  6],
       [ 9,  8,  6]], dtype=uint8)

In [17]:
vecy=np.float32(vec)

In [18]:
vecy

array([[13., 13.,  1.],
       [13., 13.,  3.],
       [16., 13.,  8.],
       ...,
       [ 9.,  8.,  6.],
       [ 9.,  8.,  6.],
       [ 9.,  8.,  6.]], dtype=float32)

In [19]:
criteria=(cv.TERM_CRITERIA_MAX_ITER,100,1)

In [20]:
k=3
attempts=100

In [24]:
compactness,label,center=cv.kmeans(vecy,k,None,criteria,attempts,cv.KMEANS_PP_CENTERS)
center

array([[204.25311 , 228.37389 ,  82.57298 ],
       [ 28.092161,  36.097206,  16.771368],
       [105.0061  , 139.90024 ,  35.738934]], dtype=float32)

In [25]:
center

array([[204.25311 , 228.37389 ,  82.57298 ],
       [ 28.092161,  36.097206,  16.771368],
       [105.0061  , 139.90024 ,  35.738934]], dtype=float32)

In [27]:
centery=np.uint8(center)

In [28]:
centery

array([[204, 228,  82],
       [ 28,  36,  16],
       [105, 139,  35]], dtype=uint8)

In [29]:
res=centery[label.flatten()]
res_img=res.reshape((imgrgh.shape))

In [30]:
res_img

array([[[28, 36, 16],
        [28, 36, 16],
        [28, 36, 16],
        ...,
        [28, 36, 16],
        [28, 36, 16],
        [28, 36, 16]],

       [[28, 36, 16],
        [28, 36, 16],
        [28, 36, 16],
        ...,
        [28, 36, 16],
        [28, 36, 16],
        [28, 36, 16]],

       [[28, 36, 16],
        [28, 36, 16],
        [28, 36, 16],
        ...,
        [28, 36, 16],
        [28, 36, 16],
        [28, 36, 16]],

       ...,

       [[28, 36, 16],
        [28, 36, 16],
        [28, 36, 16],
        ...,
        [28, 36, 16],
        [28, 36, 16],
        [28, 36, 16]],

       [[28, 36, 16],
        [28, 36, 16],
        [28, 36, 16],
        ...,
        [28, 36, 16],
        [28, 36, 16],
        [28, 36, 16]],

       [[28, 36, 16],
        [28, 36, 16],
        [28, 36, 16],
        ...,
        [28, 36, 16],
        [28, 36, 16],
        [28, 36, 16]]], dtype=uint8)

In [ ]:
cv.imshow('original',img)
cv.imshow('segmented',res_img)
cv.waitKey(0)
cv.destroyAllwindows()

In [ ]:
image=cv.imread('"C:/Users/SN124/image/ben 100.jfif"')
segmented_image=cv.pyrmeanShiftFilterimg(img,40,40)
cv.imshow('original_Image',image)
cv.imshow('segmented Image',segmented_image)
cv.waitKey(0)
cv.destroyAllWindows()